const Router = require('express')
const router = new Router()
const adminRouter = require('./adminRouter')
const areaRouter = require('./areaRouter')
const clientRouter = require('./clientRouter')
const quizRouter = require('./quizRouter')
const roomRouter = require('./roomsRouter')
const decorationRouter = require('./decorationRouter')
const deadlinesRouter = require('./deadlinesRouter')
const budgetRouter = require('./budgetRouter')
const buyRequestRouter = require('./buyRequestRouter')
const providerRouter = require('./providerRouter')

router.use('/admin', adminRouter)
router.use('/area', areaRouter)
router.use('/client',clientRouter )
router.use('/quiz',quizRouter)
router.use('/room',roomRouter)
router.use('/decor',decorationRouter)
router.use('/deadlines',deadlinesRouter)
router.use('/budget',budgetRouter)
router.use('/buyreq',buyRequestRouter)
router.use('/provider',providerRouter)
module.exports = router